server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include:  hystrix.stream
spring:
  application:
    name: springboot-dubbo-hystrix-consumer
  
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
 
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 5000
    orderIdKey:
      execution.isolation.thread.timeoutInMilliseconds: 2000